### ISSUE TITLE
error message "undefined"

### ISSUE THREAD

**Issue by SebastianSchultz** [Grizzelbee/ioBroker.robonect#36]
**Describe the bug**  
Sporadically I get the error message "undefined" in the ioBroker log.

**To Reproduce**  
Sorry, I have no method to reproduce the error.
I think it is produced by the status or info requests.

**Expected behavior**  
No error message :)

**Screenshots & Logfiles**  
[iobroker.log](https://github.com/Grizzelbee/ioBroker.robonect/files/13066925/iobroker.log)

**Versions:**  
 - Adapter version: 1.3.4
 - JS-Controller version: 5.0.14
 - Node version: 18.17.1
 - Operating system: Ubuntu Linux

**Additional context**  
None

**Comment by Grizzelbee** [comment]
Okay - strange.
thank you very much for the logfile .
Sometimes the polling of battery data fails and sometimes it works. When it fails it results in this ```undefined```.
I need to take a deeper look into it.

Please be patient.

**Comment by Grizzelbee** [comment]
Okay - I think I didn't made myself clear enough.
When you change the config of the adapter it gets restarted by ioBroker to initialize newly. This is what I ment in my last post.
And when I read the log correctly this "undefined" error only happens on the first run after each restart, from the second run/poll intervall on it gets the battery state correctly.

And I asked you to proof and corfirm or deny this theory.

**Comment by SebastianSchultz** [comment]
Yes your rights. The message appears every time on adapter start.
