### ISSUE TITLE
MODE: Difference between Adapter and Robonect-WebUI 

### ISSUE THREAD

**Issue by Grizzelbee** [Grizzelbee/ioBroker.robonect#37]
**Describe the bug**  
see german Forum:
https://forum.iobroker.net/topic/11834/neuer-robonect-hx-adapter/424#

**Expected behavior**  
WebUI and adapter should show the same values

**Screenshots & Logfiles**  
see forum thread

**Additional context**  
This bug needs to be investigated and confirmed!

**Comment by afuerhoff** [comment]
Hallo, dieser Fehler hat sich scheinbar auch erledigt. Ich hatte nochmal im Forum nachgelesen und hatte auch das Proxmox Container Problem mit dem Ping. Das hat auch dieses Problem gelöst.
