### ISSUE TITLE
"No connection to lawn mower (Not able to ping it). Check network connection." on every poll

### ISSUE THREAD

**Issue by Grizzelbee** [Grizzelbee/ioBroker.robonect#38]
**Describe the bug**  
The error message "No connection to lawn mower (Not able to ping it). Check network connection." appears on every poll.

See: https://forum.iobroker.net/topic/11834/neuer-robonect-hx-adapter/428#

**Additional context**  
This error needs to be investigated and confirmed.

**Comment by afuerhoff** [comment]
Hallo, dieser Fehler hat sich erledigt. Ich hatte nochmal im Forum nachgelesen und hatte auch das Proxmox Container Problem mit dem Ping.
