### ISSUE TITLE
PushService says its misconfigured - but it's not

### ISSUE THREAD

**Issue by Grizzelbee** [Grizzelbee/ioBroker.robonect#39]
**Describe the bug**  
See: https://forum.iobroker.net/topic/11834/neuer-robonect-hx-adapter/429#

**Additional context**  
This bug needs to be investigated and confirmed.

**Comment by afuerhoff** [comment]
Hallo, der Bug scheint auch keiner zu sein. Hängt wahrscheinlich alles irgendwie mit dem Ping zusammen.
Kann ebenfalls geschlossen werden.
